development:
  adapter: postgresql
  encoding: unicode
  database: eng_community_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: eng_community_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: eng_community_production
  pool: 5
